server:
  port: 8091

spring:
  main:
    banner-mode: off
  thymeleaf:
    check-template-location: false
  datasource:
    hikari:
      connection-test-query: SELECT 1
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=public}
    platform: postgres
    username: ${DB_USER:postgres}
    password: ${DB_PWD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

security:
  secret: ${JWT_SECRET:bGT2EI7sTPNymldVGDJuHuc6xDdOONKail29quWsMSw=}
  expiration-time: ${JWT_EXPIRATION_TIME:3600000}
